### ISSUE TITLE
net-ssh doesn't work with ssh-agent/requires Pageant on Windows

### ISSUE THREAD

**Issue by func0der** [net-ssh/net-ssh#754] opened 2020-04-15 12:49 UTC
Everything is explained here: https://github.com/net-ssh/net-ssh/issues/192

This is still not fixed and now also broken with Windows 10.

**Comment by mfazekas** [comment] 2020-04-15 13:06
Duplicate of: #628 
the root of issue is different unix layers on win 10, the cygwin built ruby should work with cygwin ssh agent. The WSL built ruby should work with WSL ssh agent. But from a win32 ruby we don't know how to communicate to a WSL ssh agent.

**Closed by mfazekas** 2020-04-15 13:06 UTC

**Comment by func0der** [comment] 2020-04-20 07:50
We are not talking about WSL here. We are takling about bash

```
$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

which comes with git and provides a perfectly fine socket:

```
$ echo $SSH_AUTH_SOCK
/tmp/ssh-rxxpTf8axKFv/agent.1586
```

**Comment by mfazekas** [comment] 2020-04-20 08:53
@func0der so yes it's not WSL it's msys2, but the issue is the same.

The problem is that the path `/tmp/ssh-rxxpTf8axKFv/agent.1586` and esp as a unix domain socket, does not exist on windows. There are different environments that can emulate those (cygwin, msys, wsl, mingw, etc.)

Ideally if you have a msys2 bash/ssh and msys2 based ruby should be able to communicate with it each other. 

if you can run the following in your ruby, then you can expect `net-ssh` to communicate with your agent.

```ruby
irb>require 'socket'
irb>UNIXSocket.open(ENV['SSH_AUTH_SOCK'])
```

Otherwise it's not implemented. We do accept PR-s for supporting different unix domain socket emulations on windows.


https://stackoverflow.com/questions/23086038/what-mechanism-is-used-by-msys-cygwin-to-emulate-unix-domain-sockets
