### ISSUE TITLE
zlib(finalizer): the stream was freed prematurely.

### ISSUE THREAD

**Issue by roroco** [net-ssh/net-ssh#284] opened 2015-11-21 14:32 UTC
here is my code

```
require 'net/ssh'
s = Net::SSH.start('rmt', 'root', compression: true, compression_level: 9)
s.exec!('ls -al')
```

**Comment by duffyjp** [comment] 2016-04-05 20:12
I'm getting this too, for me at the end of a Capistrano deploy:

```
...
INFO [fde8260c] Finished in 0.007 seconds with exit status 0 (successful).
zlib(finalizer): the stream was freed prematurely.
```

**Comment by mfazekas** [comment] 2016-04-07 12:23
This is not a bug you do not close the ssh cahnnel so ssh cannot close zlib so zlib complains. Please close your session properly:

```ruby
Net::SSH.start(@host, @user, compression: true, compression_level: 9) do |ssh|
ssh.exec!('ls -la')
end
```
or 

```ruby
ssh = Net::SSH.start(@host, @user, compression: true, compression_level: 9)
ssh.exec!('ls -la')
ssh.close
```

Not sure about capistrano, it should be closing it

**Closed by mfazekas** 2016-04-07 12:23 UTC

**Comment by mfazekas** [comment] 2016-04-22 04:02
Fixed on sshkit: https://github.com/capistrano/sshkit/pull/343
