### ISSUE TITLE
Ruby 2.2 64bit / Pageant / Windows / "bignum too big to convert into `long'"

### ISSUE THREAD

**Issue by ccoenen** [net-ssh/net-ssh#235] opened 2015-04-02 15:26 UTC
This issue is exclusive to the **64 bit** build of ruby 2.2.1. The 32bit build runs fine.

The current master (https://github.com/net-ssh/net-ssh/commit/3ed5b1963c1aafbb1ec239b5a0a20cc57ea92194) won't work on ruby 2.2.1-64 / Windows. It fails with this message:

```
SSHKit::Runner::ExecuteError: Exception while executing on host --redacted--: bignum too big to convert into `long'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:191:in `malloc'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:191:in `malloc_ptr'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:255:in `get_token_information'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:228:in `get_current_user'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:204:in `get_security_attributes_for_user'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:347:in `send_query'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/pageant.rb:324:in `send'
C:/Tools/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/net-ssh-3ed5b1963c1a/lib/net/ssh/authentication/agent/socket.rb:148:in `send_packet'
```

There has been some work towards 2.2 compatibility in January, so i wonder if this should actually be working or if it was not tested on 64 bit.

The latest release (v2.9.2 at the time of writing) does not work because of the removal of 'dl' in ruby 2.2.

**Comment by ccoenen** [comment] 2015-04-07 22:23
It would also be very nice to have the current master as a release (even if only 32bit works on windows), so that we don't need to pull it in from github.

**Comment by Antiarchitect** [comment] 2015-04-21 09:36
+1 Experiencing exact the same issue.

**Comment by pleaseking** [comment] 2015-04-24 05:26
This pull request is supposed to fix it: https://github.com/net-ssh/net-ssh/pull/239

**Comment by thargor** [comment] 2015-06-24 06:37
This bug is not fixed in #239 (or at least not working in v2.10.0.beta1)

**Comment by sschuberth** [comment] 2015-07-13 09:47
I'm unable to reproduce this with current master (bab03189d4460792c400511d1ba1050a9d8dc3c6) on Windows 8.1 x64, Ruby 2.2.2 x64, using Pageant for authentication. If anyone still sees this, could you please post a minimal program to trigger this issue?

**Comment by ccoenen** [comment] 2015-07-13 20:06
I use the following tiny script and the bug will turn up every other time. (Meaning it works _sometimes_).

The expected output is:

```
> C:\Tools\Ruby22-x64\bin\bundle exec C:\Tools\Ruby22-x64\bin\ruby netssh_poc.rb
ruby: 2.2.2
net-ssh: 2.10.0.beta2
--whatever your hostname is--
--whatever the id command returns--
```

*Gemfile*
```ruby
source 'https://rubygems.org'
gem 'net-ssh', git: 'git@github.com:net-ssh/net-ssh.git', ref: 'bab0318'
```

*netssh_poc.rb*
```ruby
SSH_HOST = 'example.com'
SSH_USER = 'root'

puts "ruby: #{RUBY_VERSION}"

# intentionally delayed so the above will always print.
require 'net/ssh'
puts "net-ssh: #{Gem.loaded_specs['net-ssh'].version}"

Net::SSH.start(SSH_HOST, SSH_USER) do |ssh|
  puts ssh.exec!('hostname')
  puts ssh.exec!('id')
end
```

**Comment by ccoenen** [comment] 2015-07-13 21:02
On **64bit**, i've had 8 successes (sometimes in little streaks) and 15 errors.

On **32bit**, 20 out of 20 worked just fine.

**Comment by pleaseking** [comment] 2015-07-14 05:42
I managed to reproduce it either, but only sometimes, and don't see much logic. Restarting Pageant usually helps. Seems like non-initialized variable or something. Will try to take a closer look.

**Comment by shirosaki** [comment] 2016-03-30 02:38
This patch may solve the issue.
`preturn_length.ptr.to_i` is 8 bytes since pointer size is 8 bytes on 64bit OS.
The length should be long (4 bytes).

```patch
diff --git a/lib/net/ssh/authentication/pageant.rb b/lib/net/ssh/authentication/pageant.rb
index f0bf758..8a5bca2 100644
--- a/lib/net/ssh/authentication/pageant.rb
+++ b/lib/net/ssh/authentication/pageant.rb
@@ -254,7 +254,7 @@ module Net; module SSH; module Authentication
         Win.GetTokenInformation(token_handle,
                                 token_information_class,
                                 Win::NULL, 0, preturn_length)
-        ptoken_information = malloc_ptr(preturn_length.ptr.to_i)
+        ptoken_information = malloc_ptr(preturn_length.to_s(Win::SIZEOF_DWORD).unpack('L')[0])
 
         # This call is going to write the requested information to
         # the memory location referenced by token_information.
```

**Comment by mfazekas** [comment] 2016-06-20 08:13
Can anyone confirm that https://github.com/net-ssh/net-ssh/pull/385 is a good fix for the issue? 
If you have bundler then 

```
gem 'net-ssh', :github => 'elconas/net-ssh', :branch => 'fix_issue_235-rebase2'
```
should get that patched version.

**Comment by ccoenen** [comment] 2016-06-20 09:50
https://github.com/net-ssh/net-ssh/pull/385#issuecomment-227098016

**Closed** 2016-07-23 15:54 UTC

**Comment by johnnyshields** [comment] 2016-08-01 19:35
@mfazekas this seems to be a critical issue on Windows 10. since 4.0.0-beta1 is also having issues on windows to would it be possible to backport the fix in #385 and release as v3.2.1?

**Comment by vtanathip** [comment] 2016-08-12 16:09
Hi All, I still have this error (bignum too big to convert into 'long') on 

net-ssh: 3.2.0
gem: 2.4.5.1
ruby: 2.2.4p230

I try to connect my AWS cloud via ssh

Has anyone an Idea?

Thanks in advance

**Comment by mfazekas** [comment] 2016-08-12 16:24
Can you please try 3.2.1.beta1 or 4.0.0.beta2 only those has the fix intergrated.

**Comment by vtanathip** [comment] 2016-08-12 16:42
Hi @mfazekas , the problem is resolved!!!!.

Thanks for the advice. It will help many people during this time :+1:

**Comment by johnnyshields** [comment] 2016-08-12 16:52
@mfazekas appreciated if you can release 3.2.1
