### ISSUE TITLE
Request for documentation/help

### ISSUE THREAD

**Issue by dkowis** [net-ssh/net-ssh#622] opened 2018-07-24 20:46 UTC
It's not a bug, but I can't find a better way of asking for help as to how to do a thing.

Specifically, I would like to do this: https://net-ssh.github.io/ssh/v1/chapter-5.html#s5

I found that documentation, and I tried to adapt it somewhat for v2+, but things don't seem to work. I can execute an arbitrary command, which is excellent. When I try to drop to an interactive terminal session, it doesn't seem to work. In theory, it should work, but it appears that the send_data never actually sends data. I have been having trouble finding examples for this.

My ultimate goal is to have an "ssh replacement" that also sets up the box I'm logging into for me. I'll add some skeleton files like screenrc and bashrc, and then start up a shell. If I've already added those files, then I just get my shell. This way I don't have to think about provisioning the box first. 

Code I'm trying to get working follows:

```ruby
class Helper
    def stdin_buffer(enable)
      return unless defined?(Termios)
      attr = Termios::getattr($stdin)
      if enable
        attr.c_lflag |= Termios::ICANON | Termios::ECHO
      else
        attr.c_lflag &= ~(Termios::ICANON | Termios::ECHO)
      end
      puts "Setting terminal attributes!"
      Termios::setattr($stdin, Termios::TCSANOW, attr)
    end

    def connect(hostname, environment)

      # load the YAML config
      begin
        config = YAML::load(File.open(File.expand_path('~/.config/assh/config.yml'))) || {}

        pp config
      rescue Errno::ENOENT => e
        puts 'Unable to find config file! Create ~/.config/assh/config.yml'
        puts e
      end

      # translate the typed name into a real hostname, based on the config

      host_pattern = config['environments'][environment]['hostPattern']
      user = config['environments'][environment]['userName'] || config['global']['userName']

      real_hostname = host_pattern.gsub('$1', hostname)

      begin
        stdin_buffer false

        Net::SSH.start(real_hostname, user) do |ssh|

          # Do everything in a channel?
          ssh.open_channel do |channel|
            channel.exec('cat /proc/cpuinfo') do |ch, success|
              channel.on_data do |ch, data|
                $stdout.print data
              end

              channel.on_extended_data do |ch, type, data|
                $stderr.print data
              end

              channel.on_close do |ch|
                $stdout.puts '/proc/cpuinfo channel is closing'
              end
            end
          end

          #TODO: how do I wait for the first operation to happen before I try to do the other stuff.
          # Of course, it doesn't matter if I can't hook stdin and stdout up...

          # Get a second channel that we're going to use for the terminal emulation
          ssh.open_channel do |channel|

            #get a PTY, and hook it to my stdin/out/err

            # stealing stuff from other rubygems, hopefully getting it right....
            channel.request_pty(:modes => { Net::SSH::Connection::Term::ECHO => 0 }) do |ch, success|
              if success
                puts "ACHIEVED A PTY"
              else
                puts "NO PTY FOR YOU"
              end
            end

            shell_loop = true

            channel.on_data do |ch, data|
              # something on stdout
              $stdout.print data
              $stdout.flush
            end

            channel.on_extended_data do |ch, type, data|
              # something on stderr
              $stderr.print data
              $stderr.flush
            end

            channel.on_close do |ch|
              # channel is closing
              puts "CHANNEL IS CLOSING!"
              shell_loop = false
            end

            channel.on_process do |ch|
              print 'processing'
            end

            channel.send_channel_request "shell" do |ch, success|
              if success
                puts 'USER SHELL STARTED SUCCESSFULLY'
              else
                puts 'UNABLE TO START USER SHELL'
              end

              #IO thread needs to be within the context of this channel?
              io_thread = Thread.new do
                loop do
                  # shell loop will be false once the close event happens.
                  break unless shell_loop
                  if IO.select([$stdin], nil, nil, 0.01)
                    data = $stdin.sysread(1)
                    channel.send_data data
                  end
                end
              end

            end


            # channel.on_process do |ch|
            #   puts 'processing...'
            #   if IO.select([$stdin], nil, nil, 0.01)
            #     data = $stdin.sysread(1)
            #     channel.send_data data
            #   end
            # end
          end

          # keep it alive and keep working until it's closed.
          # DOes this keep the channel processing?
          puts "SSH LOOP STARTED"
          ssh.loop
          puts "DONE WITH SSH LOOP"
        end

      ensure
        puts "Resetting terminal"
        stdin_buffer false
      end

      # connect
      # Update the skeleton of files, if needed
      # Drop to a regular old SSH session (ideally, without having to log in again)


    end
  end
```

**Comment by i5okie** [comment] 2018-10-31 01:29
I found that stdin_buffer breaks it all.
And without it, pressing Enter/Return ends up sending a NewLine character instead of CR.

Have you been able to figure this out yourself yet?
I've tried just about everything I could think of.

**Comment by i5okie** [comment] 2018-11-01 15:47
I've made a bit of progress yesterday.

add require 'io/console'
and replace the your io_thread block with
```ruby
ch.on_process do |channel|
  ch.send_data $stdin.getc
end
```

I've also slightly modified the stdin_buffer block:
```ruby
def stdin_buffer(enable)
  return unless defined?(Termios)
  attr = Termios::getattr($stdin)

  if enable
    attr.c_lflag |= Termios::ICANON | Termios::ECHO
  else
    attr.c_lflag &= ~(Termios::ICANON | Termios::ECHO | Termios::ONLCR)
    # attr.c_iflag |= Termios::ONLCR
  end

  Termios::setattr($stdin, Termios::TCSANOW, attr)
end  
```

This is a bit illusive, as it appears to work. except now the issue is, have to press Enter twice.

**Comment by mfazekas** [comment] 2019-01-06 12:12
I'm sorry but stackoverflow is a much better place for such questions, so i'm closing it for now

**Closed by mfazekas** 2019-01-06 12:12 UTC
