### ISSUE TITLE
OpenSSL 3.x library support

### ISSUE THREAD

**Issue by voxik** [net-ssh/net-ssh#843] opened 2021-11-23 09:52 UTC
OpenSSL 3.x was released a while ago and there is ruby/openssl/pull/399 in the works. Testing this on Fedora, I observe more then 400 test failures testing with net-ssh-6.1.0. So lets start with this one:

~~~
  1) Error:
Transport::Kex::TestDiffieHellmanGroupExchangeSHA1#test_exchange_keys_should_return_expected_results_when_successful:
OpenSSL::PKey::DHError: OpenSSL::PKey::DH is immutable on OpenSSL 3.0; use OpenSSL::PKey.generate_key instead
    /usr/share/ruby/openssl/pkey.rb:85:in `generate_key!'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:72:in `generate_key'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:108:in `new'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:108:in `dh'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group_exchange_sha1.rb:77:in `exchange!'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:21:in `test_exchange_keys_should_return_expected_results_when_successful'
~~~

Obviously, this is due to https://github.com/ruby/openssl/pull/399/files#diff-eb733a1afb0b7a687c10db7df77cdeaeadde4e1c9212850f116a0c44a90ead85R104

**Comment by voxik** [comment] 2021-11-23 10:45
Another interesting case is this:

~~~
  1) Error:
Authentication::TestAgent#test_add_dsa_cert_identity:
OpenSSL::PKey::PKeyError: EVP_PKEY_keygen: bad ffc parameters
    /usr/share/ruby/openssl/pkey.rb:166:in `generate_key'
    /usr/share/ruby/openssl/pkey.rb:166:in `generate'
    /usr/share/ruby/openssl/pkey.rb:173:in `new'
    test/authentication/test_agent.rb:273:in `test_add_dsa_cert_identity'
~~~

The error comes from here:

https://github.com/net-ssh/net-ssh/blob/a45f54fe1de434605af0b7195dd9a91bccd2cec5/test/authentication/test_agent.rb#L274

The issue is the short key length. However, extending the length to `1024` produces different error:

~~~
  1) Error:
Authentication::TestAgent#test_add_dsa_cert_identity:
OpenSSL::PKey::DSAError: bad sig size
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/openssl.rb:115:in `ssh_do_sign'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/authentication/certificate.rb:91:in `sign!'
    test/authentication/test_agent.rb:414:in `make_cert'
    test/authentication/test_agent.rb:273:in `test_add_dsa_cert_identity'
~~~

There seems to be similar issue discussed here:

https://www.mail-archive.com/openssl-users@openssl.org/msg71145.html

And if I understand this discussion correctly, it seem that the condition:

https://github.com/net-ssh/net-ssh/blob/a45f54fe1de434605af0b7195dd9a91bccd2cec5/lib/net/ssh/transport/openssl.rb#L127

should not be applied anymore.

**Comment by voxik** [comment] 2021-11-23 11:04
Then there are hundreds of issues such as:

~~~
  1) Error:
Transport::TestCipherFactory#test_blowfish_cbc_for_decryption:
OpenSSL::Cipher::CipherError: unsupported
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/cipher_factory.rb:49:in `initialize'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/cipher_factory.rb:49:in `new'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/cipher_factory.rb:49:in `get'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/test_cipher_factory.rb:291:in `decrypt'
    /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/test_cipher_factory.rb:83:in `test_blowfish_cbc_for_decryption'
~~~

**Comment by terceiro** [comment] 2022-02-02 22:42
ruby/openssl 3.0 has since been released. I have also tested this on Debian with Ruby 3.0 and openssl 3.0.0. However the only test failures that I see are the `OpenSSL::PKey::DSAError: bad sig size` ones:

```
$ rake test
Skipping packet stream test for idea-cbc
Run options: --seed 48217

# Running:

...................................................................................E.....................................................E..........E..EE.E..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 4.020977s, 377.2715 runs/s, 1270.5867 assertions/s.

  1) Error:
Authentication::TestAgent#test_add_dsa_cert_identity:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_agent.rb:417:in `make_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_agent.rb:274:in `test_add_dsa_cert_identity'

  2) Error:
Authentication::TestKeyManager#test_sign_with_agent_originated_key_should_be_signable_through_explicitly_loaded_cert:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:319:in `rsa_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:217:in `test_sign_with_agent_originated_key_should_be_signable_through_explicitly_loaded_cert'

  3) Error:
Authentication::TestKeyManager#test_each_identity_should_load_from_explicit_cert_file_given_matching_key_is_loaded:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:319:in `rsa_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:87:in `test_each_identity_should_load_from_explicit_cert_file_given_matching_key_is_loaded'

  4) Error:
Authentication::TestKeyManager#test_each_identity_should_load_from_implicit_cert_file:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:319:in `rsa_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:75:in `test_each_identity_should_load_from_implicit_cert_file'

  5) Error:
Authentication::TestKeyManager#test_each_identity_should_ignore_explicit_cert_file_unless_matching_key_is_avaiable:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:319:in `rsa_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:103:in `test_each_identity_should_ignore_explicit_cert_file_unless_matching_key_is_avaiable'

  6) Error:
Authentication::TestKeyManager#test_each_identity_should_match_explicit_keycert_with_agent_provided_identity:
OpenSSL::PKey::DSAError: bad sig size
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/transport/openssl.rb:127:in `ssh_do_sign'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/lib/net/ssh/authentication/certificate.rb:92:in `sign!'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:319:in `rsa_cert'
    /home/terceiro/src/debian/ruby-team/ruby-net-ssh/test/authentication/test_key_manager.rb:140:in `test_each_identity_should_match_explicit_keycert_with_agent_provided_identity'

1517 runs, 5109 assertions, 0 failures, 6 errors, 0 skips
rake aborted!
Command failed with status (1)

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by voxik** [comment] 2022-02-22 08:47
Even with Ruby 3.1 (without me possibly introducing some issues by backporting the patches), the net-ssh test suite fails a lot:

~~~
1549 runs, 3673 assertions, 28 failures, 449 errors, 0 skips
~~~

The specific issues can be seen in build.log on Koschei [[1]].

Nevertheless, I find surprising that Debian would not report issues such as `OpenSSL::PKey::PKeyError: dsa#set_pqg= is incompatible with OpenSSL 3.0`. Are you really sure you are running the tests against OpenSSL 3.0?

Actually, since the beginning, I was speaking about OpenSSL 3.0 library [[2]], not OpenSSL 3.0 gem [[3]]. That might be part of confusion.

[1]: https://koschei.fedoraproject.org/package/rubygem-net-ssh
[2]: https://www.openssl.org/
[3]: https://rubygems.org/gems/openssl

**Comment by terceiro** [comment] 2022-02-22 12:58
> Actually, since the beginning, I was speaking about OpenSSL 3.0 library [[2](https://www.openssl.org/)], not OpenSSL 3.0 gem [[3](https://rubygems.org/gems/openssl)]. That might be part of confusion.

yes, that's it. We are on the openssl gem 3.0 already in preparation for openssl 3.0, but openssl is still 1.1*

**Comment by lucaskanashiro** [comment] 2022-03-07 15:18
In Ubuntu, where we already moved to the OpenSSL 3.0 library I can see something similar to what was observed in Fedora:

```
1494 runs, 3679 assertions, 28 failures, 395 errors, 0 skips
```

**Comment by popeda97** [comment] 2022-03-14 19:32
> OpenSSL 3.x was released a while ago and there is [ruby/openssl/pull/399](https://github.com/ruby/openssl/pull/399) in the works. Testing this on Fedora, I observe more then 400 test failures testing with net-ssh-6.1.0. So lets start with this one:
> 
> ```
>   1) Error:
> Transport::Kex::TestDiffieHellmanGroupExchangeSHA1#test_exchange_keys_should_return_expected_results_when_successful:
> OpenSSL::PKey::DHError: OpenSSL::PKey::DH is immutable on OpenSSL 3.0; use OpenSSL::PKey.generate_key instead
>     /usr/share/ruby/openssl/pkey.rb:85:in `generate_key!'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:72:in `generate_key'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:108:in `new'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:108:in `dh'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group_exchange_sha1.rb:77:in `exchange!'
>     /builddir/build/BUILD/net-ssh-6.1.0/usr/share/gems/gems/net-ssh-6.1.0/test/transport/kex/test_diffie_hellman_group1_sha1.rb:21:in `test_exchange_keys_should_return_expected_results_when_successful'
> ```
> 
> Obviously, this is due to https://github.com/ruby/openssl/pull/399/files#diff-eb733a1afb0b7a687c10db7df77cdeaeadde4e1c9212850f116a0c44a90ead85R104

**Comment by ernestask** [comment] 2022-04-12 06:54
Correction: #857

**Comment by proigor** [comment] 2022-04-28 12:35
I've upgraded my laptop to ubuntu 22.04 and no longer able to deploy using capistrano due to this openssl 3.0 issue.
I'm not sure how to proceed, should I downgrade or any estimate when this will be fixed and the new net-ssh release will be.
And advise much appreciated.

**Comment by lucaskanashiro** [comment] 2022-04-28 12:45
@proigor unfortunately net-ssh is still broken in Ubuntu 22.04, we are waiting for the proposed changes (see #857) to be reviewed and merged to actually fix it. We are trying to avoid patching it by ourselves without the upstream maintainers blessing and potentially make it worse. Hopefully, it will not take too long.

**Comment by fwininger** [comment] 2022-04-28 21:00
I have a fix all unit tests. I think we can have a stable master branch tomorrow. After that @mfazekas can do the release.

**Comment by fwininger** [comment] 2022-04-29 12:45
#864 close this issue @lucaskanashiro

**Closed by fwininger** 2022-04-29 12:45 UTC

**Comment by lucaskanashiro** [comment] 2022-04-29 15:24
Thanks @fwininger :)

**Comment by guss77** [comment] 2022-06-28 13:56
I still have an issue with net-ssh and OpenSSL 3.0 - I wonder if this is the correct place to report this:

With net-ssh 7.0.1, trying to use a private key (that works well with openssh client 8.9p1 on Ubuntu 22.04), I get this error:

```
ERROR -- net.ssh.authentication.key_manager[44d4]: could not load private key file `/home/guss77/.ssh/private.pem': 
OpenSSL::PKey::PKeyError (rsa#set_key= is incompatible with OpenSSL 3.0)
```

This is when specifying the private key to use in the `~/.ssh/config` file. If I load the private key into the SSH agent, it works fine.

**Comment by dentarg** [comment] 2022-06-28 18:23
@guss77 I think that should be a new issue (maybe with some code showing how to reproduce?) 

Looks to me that [`read_private_keyblob`](https://github.com/net-ssh/net-ssh/blob/39aa8dfc97e87f83626f382bea1c804fef6367d5/lib/net/ssh/buffer.rb#L265-L267) wasn't updated like [`read_keyblob`](https://github.com/net-ssh/net-ssh/pull/864/files#diff-79b756ce17e5c31d78be6bb539a0e3b340ebb73f97a76877a70634e762f36de2) was.

**Comment by guss77** [comment] 2022-06-30 09:19
> @guss77 I think that should be a new issue (maybe with some code showing how to reproduce?)

Thank you, I opened a new issue #874
