### ISSUE TITLE
Windows Openssh agent 

### ISSUE THREAD

**Issue by attobyte** [net-ssh/net-ssh#661] opened 2019-02-19 01:52 UTC
### Expected behavior

Have net-ssh use Windows 10 default Openssh agent. Windows 10 installs OpenSSH by default and has a windows service for the SSH Agent. 

When connecting to a 2nd host (2nd channel?) net-ssh fails to communicate with Windows agent.

Windows OpenSSH agent is running
Identities are added via `ssh-add` 
Identities show with `ssh-add -l`

### Actual behavior

The initial connections works but fails connecting to another site. I am using bitbucket to clone a repository.

### System configuration

**Versions:**
`net-ssh (5.1.0)`
`ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]`

Error from **/var/log/secure** from running script below.

```
Feb 19 01:50:04 ip-172-31-45-65 sshd[20880]: Accepted publickey for railsapp from 127.0.0.1 port 56861 ssh2: RSA SHA256:NeD8+Mk6VQx8opknG4i4f6jQZI5JisDxa6PZs5MEK48
Feb 19 01:50:04 ip-172-31-45-65 sshd[20880]: pam_unix(sshd:session): session opened for user railsapp by (uid=0)
Feb 19 01:50:05 ip-172-31-45-65 sshd[20898]: channel 2: open failed: connect failed: could not connect to authentication agent
Feb 19 01:50:05 ip-172-31-45-65 sshd[20880]: pam_unix(sshd:session): session closed for user railsapp
```

### Example App

Please provide an example script that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

You can use this as stating point:

```ruby
require 'net/ssh'

Net::SSH.start("host", "user", { :forward_agent => true }) do |ssh|
    result = ssh.exec!("git ls-remote git@bitbucket.org:someTeam/someRepo.git")
    puts result
end
```

**Comment by attobyte** [comment] 2019-02-19 03:47
Duplicate issue

**Comment by mfazekas** [comment] 2019-02-19 07:16
@attobyte thanks for the report. Out of curiosity which issue does it duplicates?

**Comment by attobyte** [comment] 2019-02-19 11:55
@mfazekas Found [issue 628](https://github.com/net-ssh/net-ssh/issues/628) after I created my report.

**Comment by mfazekas** [comment] 2019-04-13 10:45
@attobyte  thanks for the clarification, i'm closing this as sounds a duplicate of #628

**Closed by mfazekas** 2019-04-13 10:45 UTC
