### ISSUE TITLE
Unable to connect to an ssh-agent on Windows

### ISSUE THREAD

**Issue by vladyslav-androshchuk** [net-ssh/net-ssh#949] opened 2024-07-24 10:21 UTC
Hello!

Beforehand - I read most of related topics and issues related to this topic. Still, I am unable to make `Net::SSH.start` work with ssh-agent on Windows.

### Expected behavior

When ssh-agent is running and key added, `Net::SSH.start` should connect to an agent without problems.

### Actual behavior

We have tho different behaviors depending on OpenSSL implementation we are using:

1. **Windows bundled OpenSSL.** Because it's a service, when running the `SSH_AGENT_PID` and `SSH_AUTH_SOCK` are not set, and we are getting an error `net.ssh.authentication.agent[19dc]: could not connect to ssh-agent: pageant process not running`, despite `ssh-add -l` returning our keys successfully.
2. **Git bundled OpenSSL.** In this case, we have the pipe set correctly with both env variables. But during  `Net::SSH.start`  we are getting other error - `net.ssh.authentication.agent[19dc]: could not connect to ssh-agent: No connection could be made because the target machine actively refused it. - connect(2) for C:/TeamcityAgent/temp/buildTmp/ssh412.....sock`.

To use _Git bundled OpenSSL_ we need to remove `%SYSTEMROOT%\System32\OpenSSH\` from `PATH` environment variable and add `C:\Program Files\Git\usr\bin` to it. Also, we need to disable windows `ssh-agent` service and set it to `StartupType - Manual`.

### System configuration

- net-ssh - v7.2.3.
- Ruby - v3.3.0.1 (Chocolatey).
- Windows 11 (latest patches).
- Git - v2.45.2.windows.1 (Chocolatey).
- Windows `ssh-agent` service is set to `StartupType - Manual`.

Worth mention that we are using a `fastlane` with `net-ssh` gem and run it from a TeamCity agent (which starts given ssh-agent and add ssh keys, and run `bundle exec fastlane ...` using `cmd.exe`). But looks like the same, just running pure ruby code.

### Example App

```ruby
require 'net/ssh'

cdn_host = '...'
cdn_user = '...'

Net::SSH.start(cdn_host, cdn_user, verbose: Logger::DEBUG, auth_methods: ['publickey']) do |ssh|
end
```

**Comment by vladyslav-androshchuk** [comment] 2024-07-24 10:40
@mfazekas Hello! Is any chance you can look on this topic? Maybe any advice?

**Comment by mfazekas** [comment] 2024-07-24 12:24
@vladyslav-androshchuk See  #628 

https://github.com/net-ssh/net-ssh/issues/628#issuecomment-418634783
https://github.com/net-ssh/net-ssh/issues/754#issuecomment-614028094

> When ssh-agent is running and key added, Net::SSH.start should connect to an agent without problems.

Which ssh-agent and which Net::SSH (aka which ruby)?!

If ssh-agent is WSL ssh-agent. and Net::SSH is running in ruby build in WSL then it should work. 

As for background Net-SSH communicates with SSH agent via UNIX domain sockets. Which is low level primitive on UNIX, but on windows there are different approaches to emulate it. And if you're ruby build uses incompatible method of Unix domain sockets to the ssh-agent then they won't be able to communicate. Like a cygiwin ruby build cannot communicate with a WSL build ssh-agent.


https://github.com/net-ssh/net-ssh/blob/6fe0040eb6b4b45ff1eeca58567f7077e02d3c05/lib/net/ssh/authentication/agent.rb#L85-L102

You'll need to examine values of ENV['SSH_AUTH_SOCK'] this should be set when running the ssh agent and try to connect it with ruby's `UNIXSocket.open( ... )`

**Comment by vladyslav-androshchuk** [comment] 2024-07-24 12:59
> @vladyslav-androshchuk See #628
> 
> [#628 (comment)](https://github.com/net-ssh/net-ssh/issues/628#issuecomment-418634783) [#754 (comment)](https://github.com/net-ssh/net-ssh/issues/754#issuecomment-614028094)
> 
> > When ssh-agent is running and key added, Net::SSH.start should connect to an agent without problems.
> 
> Which ssh-agent and which Net::SSH (aka which ruby)?!
> 
> If ssh-agent is WSL ssh-agent. and Net::SSH is running in ruby build in WSL then it should work.
> 
> As for background Net-SSH communicates with SSH agent via UNIX domain sockets. Which is low level primitive on UNIX, but on windows there are different approaches to emulate it. And if you're ruby build uses incompatible method of Unix domain sockets to the ssh-agent then they won't be able to communicate. Like a cygiwin ruby build cannot communicate with a WSL build ssh-agent.
> 
> https://github.com/net-ssh/net-ssh/blob/6fe0040eb6b4b45ff1eeca58567f7077e02d3c05/lib/net/ssh/authentication/agent.rb#L85-L102
> 
> You'll need to examine values of ENV['SSH_AUTH_SOCK'] this should be set when running the ssh agent and try to connect it with ruby's `UNIXSocket.open( ... )`

System configuration:
- net-ssh - v7.2.3.
- Ruby - v3.3.0.1 (from Chocolatey).

I tried 2 ssh agents: _Windows bundled OpenSSL_ and _Git bundled OpenSSL (unix one)_. In the second case, as I described above I have `SSH_AUTH_SOCK` set. But when opening a socket, I'm getting:

> _net.ssh.authentication.agent[19dc]: could not connect to ssh-agent: No connection could be made because the target machine actively refused it. - connect(2) for C:/TeamcityAgent/temp/buildTmp/ssh412.....sock_

**Comment by mfazekas** [comment] 2024-07-24 13:20
What is `ruby -v` and `git -v`?  
But ultimately if your ruby version cannot open the value of SSH_AUTH_SOCKET with `UnixSocket.open(...)` then what do you expect  `net-ssh` to do? 
Net ssh is running inside ruby, and if the ruby environment cannot connect to ssh-agent via `SSH_AUTH_SOCKET` then `net-ssh` will not be able to either.

**Comment by vladyslav-androshchuk** [comment] 2024-07-24 13:23
> What is `ruby -v` and `git -v`? But ultimately if your ruby version cannot open the value of SSH_AUTH_SOCKET with `UnixSocket.open(...)` then what do you expect `net-ssh` to do? Net ssh is running inside ruby, and if the ruby environment cannot connect to ssh-agent via `SSH_AUTH_SOCKET` then `net-ssh` will not be able to either.

`git -v`:
> _git version 2.45.2.windows.1_

`ruby -v`:
> _ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x64-mingw-ucrt]_

`UnixSocket.open(...)` produces the same:

> _net.ssh.authentication.agent[19dc]: could not connect to ssh-agent: No connection could be made because the target machine actively refused it. - connect(2) for C:/TeamcityAgent/temp/buildTmp/ssh412.....sock_

**Comment by mfazekas** [comment] 2024-07-24 16:35
@vladyslav-androshchuk thanks so much for looking into it. I understand it's frustrating that you installed both with the same method and they do not work together. 

I see that ruby is using mingw and not sure about git.

https://www.softpost.org/c-language/differences-between-cygwin-mingw-wsl-windows-subsystem-for-linux-msys2-and-git-bash#google_vignette
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
https://bugs.ruby-lang.org/issues/19135

This seems to be in ruby 3.2:
https://docs.ruby-lang.org/en/3.3/NEWS/NEWS-3_2_0_md.html

Not sure if git part is using this AF_SOCKET or not.

Sorry I'm closing the issue as there is not really much we can do unless ruby can open the socket, then net-ssh will not be able to open it either.

**Comment by mfazekas** [comment] 2024-07-24 16:35
Duplicate of https://github.com/net-ssh/net-ssh/issues/628

**Closed by mfazekas** 2024-07-24 16:35 UTC
