### ISSUE TITLE
Passphrase for ssh key can't be nil (bug)

### ISSUE THREAD

**Issue by detatka-kuzlatka-otevrete** [net-ssh/net-ssh#458] opened 2016-12-07 11:15 UTC
Please apply the attached fix for ssh keys without a passphrase, now the check in Net::SSH.start raises:
ArgumentError, "Value(s) have been set to nil: passphrase"

[net-ssh.diff.txt](https://github.com/net-ssh/net-ssh/files/636443/net-ssh.diff.txt)

**Comment by mfazekas** [comment] 2016-12-07 13:01
@detatka-kuzlatka-otevrete what is you net-ssh version? what is the usecase? why are you setting the passsphrase to nil?

**Comment by detatka-kuzlatka-otevrete** [comment] 2016-12-07 15:19
my net-ssh version is: 4.0.0.rc1

the usecase is: i am using netconf gem:
https://github.com/Juniper/net-netconf/blob/master/lib/net/netconf/ssh.rb#L28

i am not setting the passphrase to nil.

**Comment by mfazekas** [comment] 2016-12-07 15:33
Thanks for the report

This was a change in 3.0 => 4.0 it can be fixed on net-netconf side too. AFAIK there is no reason to set the passphrase to nil

**Comment by Sod-Almighty** [comment] 2016-12-10 01:43
You are mistaken. There are plenty of reasons to set things to nil.

Here's an excerpt from my code, that no longer works thanks to the _entirely unnecessary_ guard clause in 4.0:

```
Net::SSH.start @address, @user, key_data: @key && [@key],
  password: !@key && @password, passphrase: @key && @password,
  config: false, non_interactive: true
```

Result:
> Value(s) have been set to nil: key_data, passphrase (ArgumentError)

What you're essentially forcing me to do is assemble an options hash explicitly, then pass it to the call:
```
opts = { config: false, non_interactive: true }
opts[:key_data] = [@key] if @key
opts[:password] = @password unless @key
opts[:passphrase] = @password if @key
Net::SSH.start @address, @user, **opts
```
**How is this helpful?**

For that matter, what purpose is served by the guard clause in the first place?

**Comment by mfazekas** [comment] 2016-12-10 07:44
@Sod-Almighty I'd appreciate if you'd choose your words more carefully. This is an open source project where people are spending they valuable free time. It's possible and likely that are wrong decisions made, but please focus on understanding the decisions then explaining why they are wrong.

See #355, #316


If you still want to do in one line you can do this:
```ruby
Net::SSH.start @address, @user, {key_data: @key && [@key],
  password: !@key && @password, passphrase: @key && @password,
  config: false, non_interactive: true}.reject { |_,v| v.nil? }
```

The issue with nil parameters are that they are undefined, we don't mention you can pass nil in parameters. For a lot of options we blow up with strange errors in internals of net-ssh when you pass in `nil` i don't want to go and add checks so we can throw meaningfull error messages. 

I do understand your argument that it can make your ```Net::SSH.start``` invocations a bit more complex.

So i see these options:

0. keep the nil checks and  and force users to do multiline options build or compact the passed in hash
2. instead of failing just issue warning that the options were nil is now deprecated
3. relax the nil checks (like `passpharse`)
4. make nil checks only where we know we have issue like the ```keys: [env["Foo"]]```  case (btw i don't think the current code protects against that)
5. add an options to disable those checks (like ```allow_nil_arguments: true```)

@KaneMorgan what's your take on this?

**Comment by Sod-Almighty** [comment] 2016-12-10 16:58
> I'd appreciate if you'd choose your words more carefully

...what? I was polite and reasonable. I asked what the purpose of the guard clause was. I explained the problems caused by it. I did not insult anyone or the project.

I cannot choose my words any more carefully than I did. And frankly, given your objection to my perfectly reasonable words, I'm considering being _less_ careful.

**Comment by KaneMorgan** [comment] 2016-12-10 17:07
So it already fails early if the option hash has values that aren't allowed and I think its good to fail early if its in an invalid state. But the problem here seems to be that it can be a valid state and have password set to nil if they are using keys or passphrase set to nil if there is no passphrase.

We don't know which authentication method was intended so it seems to just try all of them. 

Good spot on 3 I think the current code would miss that - but I'm not sure how it should behave, setting a key explicitly to nil is probably a mistake but if thats not the key you happen to need then you may be able to connect anyway. My feeling is it should probably throw the exception here.

I think i like either option 1 which provides some helpful output in the case of a mistake but doesn't stop it if it was intentional, or 2

**Comment by KaneMorgan** [comment] 2016-12-10 17:30
@Sod-Almighty thanks for the report and providing an example which illustrates your point. I'm sure any offence was completely unintentional.

I think use of the second person during criticism can be interpreted the wrong way "you did something" vs "this is the situation", the former can make people defensive again I'm sure no offence was intended

**Comment by mfazekas** [comment] 2016-12-11 11:47
@KaneMorgan i agree let's change this to warning, and make sure it actually catches `keys: [ENV["foo"]]` #316 also allow nil for both passphrase and password

**Comment by Sod-Almighty** [comment] 2016-12-11 17:27
What kind of warning? Printing a warning to the console every time the function is called is not acceptable. Library functions should not print to the console, **ever**.

A warning is just as bad as an exception. Because there's no way I - or anyone else - could possibly leave their program spewing confusing warnings at the user. There needs to be a way to suppress this warning.

**Comment by mfazekas** [comment] 2016-12-11 20:37
@Sod-Almighty it's a standard practice for builtin and 3rd party ruby libraries to issue warning in case of deprecations. It's better than exception as legacy programs can continue to run without code modifications.
Of course apps can always avoid warnings by not passing nil values even if it makes their ```Net::SSH.start``` invocation a bit more complex.

**Comment by Sod-Almighty** [comment] 2016-12-13 19:21
In other words "we can either make it crash, or we can make it annoy the end-user such that you can't continue to do it even though it works".

There was NO reason for the guard clause in the first damn place; and two people have already complained about it, but you're gonna leave it in anyway. Well, thanks for nothing.

This is the attitude I adopt when people are wilfully unhelpful. Feel free to bitch about it.

**Closed** 2016-12-15 11:32 UTC
